### ISSUE TITLE
Normal users can't add widgets to their pinboards

### ISSUE THREAD

**Issue by iionly** [AU-Landing-Project/au_sets#10]
The issue is in version 2.0.0. Tested on Elgg 1.12.

The issue was reported at https://github.com/iionly/au_sets/issues/2#issuecomment-222792512 to me (I had created this repo not knowing of the existence of the repo here). The problem does not occur with AU Sets < 2.0.0 though, so it must have been introduced on the rework for 2.0.0.

**Comment by beck24** [comment]
oh ok, I didn't know about your repo either :)

**Comment by iionly** [comment]
I hadn't known about this repo here back then when I had created my repo. I had created it when updating AU Sets for Elgg 1.9. Now it's kind of obsolete. If you want to, you can grab the German translations though.

**Comment by propertunist** [comment]
i have forked this plugin and it now works in 2.x.
