### ISSUE TITLE
new widgets added to pinboards default to the final column and cannot be dragged

### ISSUE THREAD

**Issue by propertunist** [AU-Landing-Project/au_sets#11]
i have now forked this plugin and upgraded it to 2.x level. all seems well, except a minor annoyance that i also experienced back in elgg 1.8 with a version of this plugin, but that you fixed in a later version (as i recall you didn't know you had fixed it at the time!).
1. add a widget to a pinboard.
2. (it is not always added to the most appropriate column/area).
3. cannot drag new widget until page is refreshed
4. new widget may now have moved to where it should have been all along

**Comment by iionly** [comment]
Check out my updated version of Au Sets (1.8 version updated for Elgg 1.9) at https://github.com/iionly/au_sets. I think I've fixed exactly this issue already back then when I updated it to work on Elgg 1.9. Compare my code with the 1.8 version of Au Sets. Sorry about a lot of minor differences in usage of whitespaces etc. I had cleaned up the code in hope the new version would be used but that never happened. As I don't use Au Sets myself I have currently no intention to repeat the process of fixing issues I already fixed...

Look into the difference in au_sets/views/default/page/layouts/au_configurable_widgets.php with regards to the additional div (echo "<div class=\"elgg-widgets\" id=\"elgg-widget-col-$column_index\">";). I think this has something to do addition of widgets not working as intended.

Does it work in your updated version for non-admins to add widgets? If not, maybe it helps to look into the difference in the function widget_layout_perms() in au_sets/lib/hooks.php and au_sets/views/default/page/layouts/au_configurable_widgets.php with regards of usage of the $preview variable. Maybe this fixes https://github.com/AU-Landing-Project/au_sets/issues/10.
