### ISSUE TITLE
Pinboard edit form not sticky

### ISSUE THREAD

**Issue by jondron** [AU-Landing-Project/au_sets#5]
Minor inconvenience: if there is an error creating a pinboard (e.g. icon file too big) the data already entered are not retained.

**Comment by beck24** [comment]
The form is sticky for any kind of invalid/missing required field etc.  Uploading a file that exceeds the PHP upload limits prevents any action from taking place.  The error is returned before it even reaches the elgg action, so there is no chance for it to be made sticky.  This is a global minor inconvenience that will affect any form that contains a file upload element.

**Comment by jondron** [comment]
Sounds good - no worries then.

**Comment by beck24** [comment]
I did have a thought on this, probably as a separate plugin - but I think javascript can detect the file size of a selected file before the form is submitted.  I'm imagining a plugin that simply enforces the php file size limits client-side on any file upload field.
