### ISSUE TITLE
bot going well with widget manager 5.2

### ISSUE THREAD

**Issue by merilturock** [AU-Landing-Project/au_sets#9]
Hi there thank you for the lovely plugin after the widget manager 5.2 the plugin seems not going well with it i am facing lot of bugs. AU widgets nothing get displayed not able to add single widget in the AU set i keep getting error "unexpected error while performing Ajax call "

Thanks & Regards
Meril

**Comment by beck24** [comment]
Sorry, missed this for a long time.  Widget manager is currently at 8+ and that's what it's compatible with.  Closing the issue.
